# Generated by Django 5.1.2 on 2024-10-13 22:46

import BackEnd.Apps.Recipes.Utils.utils
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=13, unique=True, validators=[BackEnd.Apps.Recipes.Utils.utils.Validators.validate_code], verbose_name='Código del Medicamento')),
                ('description', models.CharField(max_length=255, unique=True, validators=[BackEnd.Apps.Recipes.Utils.utils.Validators.validate_description], verbose_name='Nombre del Medicamento')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[BackEnd.Apps.Recipes.Utils.utils.Validators.validate_price, django.core.validators.MinValueValidator(0.01)], verbose_name='Precio del Medicamento')),
                ('stock', models.CharField(max_length=10, validators=[BackEnd.Apps.Recipes.Utils.utils.Validators.validate_stock], verbose_name='Stock')),
                ('status', models.CharField(choices=[('activo', 'Activo'), ('baja', 'De Baja')], default='active', max_length=10, verbose_name='Estado del Medicamento')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
    ]
