# Generated by Django 5.1.2 on 2024-10-12 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamento',
            name='stop',
            field=models.CharField(blank=True, null=True),
        ),
    ]
