# Generated by Django 5.1.2 on 2024-10-14 00:35

import BackEnd.Apps.Recipes.Utils.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicamento',
            name='code',
            field=models.CharField(max_length=13, unique=True, validators=[BackEnd.Apps.Recipes.Utils.utils.Validators.validate_code], verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='description',
            field=models.CharField(max_length=255, unique=True, validators=[BackEnd.Apps.Recipes.Utils.utils.Validators.validate_description], verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[BackEnd.Apps.Recipes.Utils.utils.Validators.validate_price, django.core.validators.MinValueValidator(0.01)], verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='status',
            field=models.CharField(choices=[('activo', 'Activo'), ('baja', 'De Baja')], default='active', max_length=10, verbose_name='Estado'),
        ),
    ]
