# Generated by Django 5.1.2 on 2024-10-13 22:46

import BackEnd.Apps.Doctors.Utils.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc', models.CharField(max_length=13, unique=True, validators=[BackEnd.Apps.Doctors.Utils.utils.Validators.validate_ruc], verbose_name='Clinica Ruc')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la Clinica')),
            ],
            options={
                'verbose_name': 'Clínica',
                'verbose_name_plural': 'Clínicas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100, unique=True, verbose_name='Profesión')),
            ],
            options={
                'verbose_name': 'Profesión',
                'verbose_name_plural': 'Profesiones',
                'ordering': ['description'],
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=1, verbose_name='Elegir Sexo')),
                ('dni', models.CharField(max_length=10, unique=True, validators=[BackEnd.Apps.Doctors.Utils.utils.Validators.validate_dni], verbose_name='Ingresar Cédula')),
                ('first_name', models.CharField(max_length=50, validators=[BackEnd.Apps.Doctors.Utils.utils.Validators.validate_full_name], verbose_name='Ingresar Nombres')),
                ('last_name', models.CharField(max_length=50, validators=[BackEnd.Apps.Doctors.Utils.utils.Validators.validate_full_name], verbose_name='Ingresar Apellidos')),
                ('address', models.CharField(max_length=100, validators=[BackEnd.Apps.Doctors.Utils.utils.Validators.validate_address], verbose_name='Ingresar Ubicación')),
                ('birth_date', models.DateField(validators=[BackEnd.Apps.Doctors.Utils.utils.Validators.validate_birth_date], verbose_name='Ingresar Fecha Nacimiento')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo o Inactivo ?')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinicas', to='Doctors.clinic')),
                ('profession', models.ManyToManyField(to='Doctors.profession')),
            ],
            options={
                'verbose_name': 'Doctor',
                'verbose_name_plural': 'Doctores',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=8, unique=True, validators=[BackEnd.Apps.Doctors.Utils.utils.Validators.validate_license_number], verbose_name='Licencia Medica Del Doctor')),
                ('issued_date', models.DateField(validators=[BackEnd.Apps.Doctors.Utils.utils.Validators.validate_expiration_license], verbose_name='Expiración de la Licencia Medica del Doctor')),
                ('doctor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Doctors.doctor')),
            ],
            options={
                'verbose_name': 'Licencia',
                'verbose_name_plural': 'Licencias',
                'ordering': ['doctor', 'license_number'],
            },
        ),
    ]
