# Generated by Django 5.1.2 on 2024-10-14 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='clinic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinicas', to='Doctors.clinic', verbose_name='Clínica'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='profession',
            field=models.ManyToManyField(to='Doctors.profession', verbose_name='Profesión'),
        ),
    ]
