# Generated by Django 5.1.2 on 2024-10-14 01:21

import BackEnd.Apps.Doctors.Utils.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctors', '0002_alter_doctor_clinic_alter_doctor_profession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='address',
            field=models.CharField(max_length=100, validators=[BackEnd.Apps.Doctors.Utils.utils.Validators.validate_address], verbose_name='Ubicación'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='birth_date',
            field=models.DateField(validators=[BackEnd.Apps.Doctors.Utils.utils.Validators.validate_birth_date], verbose_name='Fecha Nacimiento'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='dni',
            field=models.CharField(max_length=10, unique=True, validators=[BackEnd.Apps.Doctors.Utils.utils.Validators.validate_dni], verbose_name='Cédula'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='first_name',
            field=models.CharField(max_length=50, validators=[BackEnd.Apps.Doctors.Utils.utils.Validators.validate_full_name], verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='last_name',
            field=models.CharField(max_length=50, validators=[BackEnd.Apps.Doctors.Utils.utils.Validators.validate_full_name], verbose_name='Apellidos'),
        ),
    ]
